apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevip
  namespace: kube-system
data:
  range-global: 192.168.188.240-192.168.188.250
  range-votingapp: 192.168.188.210-192.168.188.211
  range-ddd: 192.168.188.212-192.168.188.215
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: kube-vip
    app.kubernetes.io/version: v0.9.1
  name: kube-vip
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-vip
        app.kubernetes.io/version: v0.9.1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
             - matchExpressions:
               - key: kubernetes.io/hostname
                 operator: In
                 values:
                  - k8s-worker1
                  - k8s-worker2
      containers:
       - name: kube-vip
         args:
          - manager
          - --services
          - --interface=enp0s8
          - --arp
          - --leaderElection
         image: ghcr.io/kube-vip/kube-vip:v0.9.1
         imagePullPolicy: IfNotPresent
         securityContext:
           capabilities:
             add:
              - NET_ADMIN
              - NET_RAW
             drop:
              - ALL
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
